### ISSUE TITLE
Bitcode Support?

### ISSUE THREAD

**Issue by bugra271** [unity-plugins/Unity-Admob#11]
bitcode bundle could not be generated because '/Users/macintosh/Desktop/.../Libraries/Plugins/iOS/AdmobPlugin.a(AdmobAPI.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

You are saying it supports bitcode, but I can't archive the build with bitcode enabled. Any ideas?

**Comment by unity-plugins** [comment]
upgraded
