### ISSUE TITLE
 libc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper

### ISSUE THREAD

**Issue by FaiyazMdAbdul** [unity-plugins/Unity-Admob#115]
`libc++abi.dylib: terminating with uncaught exception of type Il2CppExceptionWrapper `
Getting this error only on iOS. 
App crashes after video loads . 
unity - 2018.1.8
admob - latest sdk

**Comment by unity-plugins** [comment]
New version ios removed libc++,
If your project add libc++ may fail .just remove libc++.
Admob not required libc++

**Comment by Bencomo** [comment]
Hello, 

I am facing the same issue at the moment.
Using Unity 2018.3.0f2 and the latest admob plugin.

My project does not has the libc++ library added.
@FaiyazMdAbdul did you find a solution to your problem in the end?

**Comment by FaiyazMdAbdul** [comment]
Reinstalling everything and creating a new xcode project fixed this.

**Comment by Bencomo** [comment]
Hello, in my case the problem went away when I unsubscribed from the handlers. This should be included in the documentation BTW..

    void OnDisable() // Unsubscribe to handlers;
    {
        interstitial.OnAdLoaded -= HandleInterstitialLoaded;
        interstitial.OnAdFailedToLoad -= HandleInterstitialFailedToLoad;
        interstitial.OnAdOpening -= HandleInterstitialOpened;
        interstitial.OnAdClosed -= HandleInterstitialClosed;

        rewardedAD.OnAdLoaded -= HandleRewardBasedVideoLoaded;
        rewardedAD.OnAdFailedToLoad -= HandleRewardBasedVideoFailedToLoad;
        rewardedAD.OnAdRewarded -= HandleRewardBasedVideoRewarded;
        rewardedAD.OnAdClosed -= HandleRewardBasedVideoClosed;
    }
