### ISSUE TITLE
ADMOB + GOOGLE PLAY GAMES BUİLD ERROR(RE-PACKAGE)

### ISSUE THREAD

**Issue by abdulmeLINK** [unity-plugins/Unity-Admob#118]
I tested without Admob and it is builded but when i test with in admob build give failed to re-packing error.
I don't know which one is toxic. one by one working but together don't working.
please help me.
(I'm using latest versions gpgs(9.60))
#2443 gpgs plugin

**Comment by unity-plugins** [comment]
https://github.com/unity-plugins/google-services-unity
