### ISSUE TITLE
Rewarded Videos without Rewarded

### ISSUE THREAD

**Issue by ninja546** [unity-plugins/Unity-Admob#119]
i made a rewarded video unit at AdMob and set 50 as a coin to offer to my users but why didn't I get a coin after I finished watching the video ad? did i miss something?

**Comment by unity-plugins** [comment]
I will have a check about this

**Comment by ninja546** [comment]
Maybe you need to fix weaknesses in the instructions in this plugin:

1) How do I ad event if in the admob installation section you ask not to include the admobdemo.cs file ...

2) If it is indeed required to download GoogleMobileAds.framework.zip, point it also to the link source and more detailed and clear instructions for its use.

Finally, also show how to subcribe to the rewarded ad event because I managed to load the video but failed to give the reward.

Still stuck ...

**Comment by ninja546** [comment]
in the next update there must be a demonstration of an example ad event for rewarded videos because this is very vital for most unity dev at this time

**Comment by ninja546** [comment]
The issue was made on February 12 and now May 19 has been successful. Case closed.
