### ISSUE TITLE
Issue with Smart Banner Ads 

### ISSUE THREAD

**Issue by NasirSabasoft** [unity-plugins/Unity-Admob#12]
Issue with Smart Banner Ads  not showing at all for IOS.
Because the Smart Banner Size not implemented correctly for IOs.

**Comment by unity-plugins** [comment]
Maybe you can try native banner,and define any size banner.
https://github.com/unity-plugins/Firebase-Admob-Unity
    Admob.Instance().showNativeBannerRelative(new AdSize(360,100), AdPosition.BOTTOM_CENTER, 0,"ca-app-pub-3940256099942544/2562852117","defaultNativeBanner");
It is better experience

**Comment by unity-plugins** [comment]
Updated,smart banner added.but I think native banner is better experience

**Comment by NasirSabasoft** [comment]
where from I can Download the updated plugin ?
