### ISSUE TITLE
How Can I Set Up The Type Of The Admob Ads: Personal Or Non Personal?

### ISSUE THREAD

**Issue by wooden-coder** [unity-plugins/Unity-Admob#127]
I need to provide to user the type of the ads that will be shown in the game: personal (with Android Advertising ID) or non personal.

As far as I know, it shows the personal Ads by default.

How can I set up the type of the ads during the game launch? And how can I make user be able to change his choice during runtime?

**Comment by unity-plugins** [comment]
AdProperties adProperties = new AdProperties();  
adProperties.nonPersonalizedAdsOnly(true);
ad.initSDK(adProperties);
