### ISSUE TITLE
Banner for IOS bug ! Cannot create a smartbanner again once removed.

### ISSUE THREAD

**Issue by NasirSabasoft** [unity-plugins/Unity-Admob#13]
First I create banner ad in home screen.
Admob.Instance().showBannerRelative(AdSize.SmartBanner, AdPosition.BOTTOM_CENTER, 0);
 
Now in next scene's Start function I call this bcz now I want banner to show on top of screen.

Admob.Instance().removeBanner();
Admob.Instance().showBannerRelative(AdSize.IABBanner, AdPosition.TOP_CENTER, 0);

Above code is working fine and Bottom Ad is hidden and Top add is showing alright. But
Now when I return to previous scene I again call

Admob.Instance().removeBanner();
Admob.Instance().showBannerRelative(AdSize.SmartBanner, AdPosition.BOTTOM_CENTER, 0);

Now no ad is loading at all.
Once removed an ad its not showing again. Is this a bug.?

**Comment by NasirSabasoft** [comment]
I figured this out this issue only come when I remove smartbanner and then try to create it again.

so the issue is with smart banners.

Once you create a smart banner and then remove it using removebanner methode and then again try to create smart banner it will not create.

**Comment by NasirSabasoft** [comment]
#12

**Comment by NasirSabasoft** [comment]
Lots of Bugs with SmartBanner in this version...

**Comment by unity-plugins** [comment]
fixed
