### ISSUE TITLE
XCode 8 & NSCalendarsUsageDescription

### ISSUE THREAD

**Issue by yrmike** [unity-plugins/Unity-Admob#19]
Trying to upload an update for an existing App with XCode 8. After the upload I have received this email:
"This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data."

Apparently AdMob is using it and they fixed it on their side.
Do you plan on applying the fix on your library?

https://groups.google.com/forum/#!category-topic/google-admob-ads-sdk/ios/y-IxErXawxg

**Comment by unity-plugins** [comment]
Thandks for you feedback

**Comment by unity-plugins** [comment]
upgraded

**Comment by aliens9889** [comment]
Hi everybody I have a big doubt, my friend and I we upload our first game on Google Play. Now we install Admob plugin from this link 

https://github.com/unity-plugins/Unity-Admob

We made some changes and now we want to update our game with this plugin on google play, but it doesn't let us to do that.

One of the warnings is android.Premission.READ_PHONE_STATE

and what we did was comment that line on AndroidManifest.xml

then we procedure to build the apk file and it doesn't work the error in console is this 

Error:Execution failed for task ':vG4Kids:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v7/appcompat/BuildConfig.class

If you have any information about that can help us. Please share with us. Thanks by the way for your attention
