### ISSUE TITLE
Unity Android AdMob test scene crashing

### ISSUE THREAD

**Issue by breban1** [unity-plugins/Unity-Admob#20]
I am trying to get AdMob working in my Android game, but am crashing when I would try to call the isRewardedReady function (can't recall name and I'm building right now).

I assumed I was doing something wrong, so I created a new Android Unity project, installed the package, and built the test scene that comes with the package.

Running it on an android device shows the buttons for all of the ad types, so I press "Show rewarded ad": "Unfortunately, AdMob has stopped, OK".

Everything else I have in my projects work fine on Android, so it is definitely this asset.

Anyone have any ideas?

**Comment by breban1** [comment]
Just an update:

The functions I am calling are:
           if (ad.isRewardedVideoReady())
            {
                ad.showRewardedVideo();
            }
            else
            {
                ad.loadRewardedVideo("ca-app-pub-3940256099942544/xxxxxxxxxxxx");
            }

Also in the demo, showInterstitial and showBanner/showBannerABS are working.  showNative/showNativeABS are not working.

The important one for me is the showRewardedVideo, and of course that's the one that crashes the demo app.

Using Unity v5.4.1p2. Latest package from Unity-AdMob plugin.

Unity Ads 2.0 ads framework works fine, even with this plugin installed.

**Comment by unity-plugins** [comment]
fixed
