### ISSUE TITLE
Can you show multiple banner ads at the same time?

### ISSUE THREAD

**Issue by ZenithCode** [unity-plugins/Unity-Admob#22]
Hi all,

Can you show multiple banner ads at the same time in the same app?

E.g. Left Skyscraper and Right Skyscraper.

Thanks.

**Comment by unity-plugins** [comment]
Yes.just define the banner name 

    Admob.Instance().showBannerRelative(AdSize.Banner, AdPosition.BOTTOM_CENTER, 0,"buttomBanner");
    Admob.Instance().showBannerRelative(AdSize.Banner, AdPosition.TOP_CENTER, 0,"topBanner");

**Comment by ZenithCode** [comment]
Thanks - worked right away!
