### ISSUE TITLE
Hi you can inform to the users check the script execution order on the error NullObjectReferece

### ISSUE THREAD

**Issue by vinicioslc** [unity-plugins/Unity-Admob#37]
Let users, put the script that loads the admob, ex "admobdemo" at the top of the "ExecutionOrder", in order to load the admob, always first, and do not cause errors of NullObjectReference !! I hope I have helped unsuspecting users.
(Sorry my poor english)

**Comment by unity-plugins** [comment]
That Great,Thanks
