### ISSUE TITLE
After complete video onRewarded not called

### ISSUE THREAD

**Issue by openxcellstudio** [unity-plugins/Unity-Admob#4]
handler onRewardedVideoEvent---onRewarded  never called after video finish

**Comment by openxcellstudio** [comment]
W/MediaPlayer(32188): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder

error..!!!

**Comment by unity-plugins** [comment]
how to call,ios version,unity version.

**Comment by openxcellstudio** [comment]
there is no duplicate jar file or aar file if i remove that 2 file than i can build and interstitial and banner works fine but if i add this 2 file for reward video ads than it not allow me to build

i am using unity reward video ads as third party in admob reward video so i have to add this 2 file in plugin folder

UnityAdsAdapter.jar and unity-ads.aar

please try your self
import this plugin https://github.com/googleads/googleads-mobile-unity/releases/tag/v3.0.3
and than import this plugin https://github.com/playgameservices/play-games-plugin-for-unity/tree/master/current-build

now set admob interstital banner and reward id

add unity as reward ads third party in admob

and add this 2 file => UnityAdsAdapter.jar and unity-ads.aar
from https://dl.google.com/googleadmobadssdk/adapterunityandroid.zip
and https://github.com/Applifier/unity-ads-sdk

and try to build that's it check reward video is loading and if it give rewarded event after complete video

if you solve this issue ,many developer can use it

thanks in advance

**Comment by openxcellstudio** [comment]
CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
C:/Program Files/Java/jdk1.8.0_71\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="E:/android-sdk-windows\tools" -Dfile.encoding=UTF8 -jar "E:\InstalledUnity\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/BuildConfig;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/IUnityAdsListener;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAds;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAds$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAds$2;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAds$3;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAdsDeviceLog;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAdsDeviceLog$1;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/unity3d/ads/android/UnityAdsDeviceLog$UnityAdsLogLevel;

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Translation has been interrupted
at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
at com.android.dx.command.dexer.Main.run(Main.java:277)
at com.android.dx.command.dexer.Main.main(Main.java:245)
at com.android.dx.command.Main.main(Main.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at SDKMain.main(SDKMain.java:129)
Caused by: java.lang.InterruptedException: Too many errors
at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
... 9 more
]

**Comment by nothingbuthappend** [comment]
its take much time  then developing apps I mean .
weird ..isnt it?

**Comment by unity-plugins** [comment]
Debugger really time consuming

**Comment by nothingbuthappend** [comment]
no sir implementing admob is painfull .
  Unfortunately,  worked only once  :(

**Comment by unity-plugins** [comment]
upgraded

**Comment by unity-plugins** [comment]
new version https://github.com/unity-plugins/Unity-Admob-Plugin-2
