### ISSUE TITLE
APP Crash when call Admob.Instance().loadInterstitial(); (unity 5.5.2f1)

### ISSUE THREAD

**Issue by WestFR** [unity-plugins/Unity-Admob#44]
Hello everybody !

So, i develop a little game (space shooter) and i use GooglePlayServices and Admob.
With your package, when i calll Admob.Instance().loadInterstital(); and others methods my phone produces somes crashs !

I have try somes manipulations with "AndroidManifest.xml" file for resolve my problems but this seem don't work ! I attach my code below..

Have you a solution or this is a mistake of myself ?

Thans you very much for your help !

![assembly-csharp-firstpass - pluginsandroidandroidmanifest xml - monodevelop-unity](https://cloud.githubusercontent.com/assets/21226632/24839933/974f2634-1d63-11e7-9b28-7c29a9a55780.jpg)

![prtscr capture](https://cloud.githubusercontent.com/assets/21226632/24839931/89b000e8-1d63-11e7-80ae-ae55b5a101d7.jpg)

**Comment by unity-plugins** [comment]
Any crash log?

**Comment by unity-plugins** [comment]
Or have a try the old version https://github.com/unity-plugins/Unity-Admob/blob/dd1b51bc3ae7a7c88fdcd1634784ffbc78496488/admob_unity_plugin.unitypackage
