### ISSUE TITLE
Google play don't allow the uploading of the app after adding the plugin to unity project.

### ISSUE THREAD

**Issue by boylamn** [unity-plugins/Unity-Admob#5]
After adding the plugin to the unity project it work perfectly if you build the apk file and run on device, but once you try to upload it to the google play it failed and show an error message asking for adding an icon to the apk file, even if it's already 100% added (512*512 PNG image). It seems that there is something wrong with the AndroidManifest.xml file in the plugin folder and unity failed to merge it with it's main AndroidManifest.xml.
I test it with unity 4.62 and unity 5, and in both of them the same problem exist.
Hope this bug will be fixed cuz this is the best and easiest unity admob plugin by far.

**Comment by unity-plugins** [comment]
You can edit AndroidManifest.xml and try.

**Comment by boylamn** [comment]
Thank you for your response, I edited the xml file and it's working fine now.Thanks once again.

**Comment by iSalmanZafar** [comment]
Please tell me what to edit in xml file?

**Comment by boylamn** [comment]
Just add the icon and app name paths to the manifest file and everything will work.

**Comment by unity-plugins** [comment]
xml file path
Plugins/Android/AndroidManifest.xml

**Comment by Mrunpredictable** [comment]
I'm facing the same problem, What exactly should i edit in the manifest file.

**Comment by nothingbuthappend** [comment]
Hello mister.i just succed only once for showing ads.but when tried to publish i got an error  google play wants gameicen.when try to change code; admobs not shown .can you explain which line of code must be placed and where will be?
Pls .and is there any updated xml file for using .

**Comment by unity-plugins** [comment]
merged changes commit by @Mrunpredictable to package now.

**Comment by unity-plugins** [comment]
new version https://github.com/unity-plugins/Unity-Admob-Plugin-2
