### ISSUE TITLE
Admob.Instance ().showInterstitial (); is working once

### ISSUE THREAD

**Issue by gitChriss** [unity-plugins/Unity-Admob#59]
Hey there.

I’m not sure if this is a bug, I’m doing something wrong or it’s a coincidence. But my Interstitial is loading once, after I klicked it away it does not come back when called again.

Do I need to load it again after it fired successful?

**Comment by gitChriss** [comment]
Okay, after a couple of minutes carefully considering I’ve decided to just try it and run the loadInterstitial() method again after displaying it.

And what do you think? Of course it works.

I’m leaving this here for other people afraid of just testing it. ;)

**Comment by unity-plugins** [comment]
Yes,you need call load interstitial after show one.
