### ISSUE TITLE
Reward Ad complete callback

### ISSUE THREAD

**Issue by dipanker29** [unity-plugins/Unity-Admob#68]
When I open the reward ad and watch till ad complete the ad callback is getting called in background, but the ad window is still open, and when I close the ad there is no callback.

Isn't the ad callback supposed to call when i close the ad or Ad window need to closed automatically ?

I am checking the ad with goggle test ad.

**Comment by dipanker29** [comment]
Sorry guys my bad i was calling Load Ad immediately after getting callback onRewarded and on closing Ad i was not getting any callback. After removing Load Ad i am getting callback onAdClosed.

**Comment by PEZO19** [comment]
I did something similar, destroyed the ad before it could with
`interstitial.Destroy();`

I have found that issue because of you. :)
