### ISSUE TITLE
admob not shown in my device ?even deleting old manifest but new android manifest xml not working .too.

### ISSUE THREAD

**Issue by nothingbuthappend** [unity-plugins/Unity-Admob#7]
sorry about waste your time with these simple question .but is new android manifest need to customize?
here is the code I dont know where is the problem .firstly I implemented your plugin .worked nicely in my android device.then when try to publish to google market,that cause failure about game icon .now I m  using new xml file but this time ads not shown ..if someone help I will be very appreciated..
thx.
here is the XML script;  
<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.admob.demo"
    android:versionName="1.0"
    android:versionCode="1">
  <uses-sdk android:minSdkVersion="9"
      android:targetSdkVersion="19" />
  
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
  <uses-permission android:name="android.permission.READ_PHONE_STATE" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_UPDATES" />
  
  
  <application
          android:theme="@style/UnityThemeSelector" 
           android:icon="@drawable/app_icon" 
           android:label="@string/app_name"  
           >
   <activity
            android:name="com.unity3d.player.UnityPlayerActivity"
            
              android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    
    <meta-data android:name="com.google.android.gms.version"
        android:value="8115000" />
    
    <activity
             android:name="com.google.android.gms.ads.AdActivity"
             android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
             android:theme="@android:style/Theme.Translucent" />
  </application>
</manifest>
-----------------------------

**Comment by unity-plugins** [comment]
upgraded

**Comment by unity-plugins** [comment]
new version https://github.com/unity-plugins/Unity-Admob-Plugin-2
