### ISSUE TITLE
Failed to re-package resources

### ISSUE THREAD

**Issue by shohagmist** [unity-plugins/Unity-Admob#70]
Before Adding this plug-in my APK build was fine. After integrating the SDK, I can't build my APK for the following error. Please help me. Which jar is conflicting, I can't find out.
Thank you.

 ERROR_LOG_STARTS

CommandInvokationFailure: Failed to re-package resources.
D:\Android\sdk\build-tools\27.0.1\aapt.exe package --auto-add-overlay -v -f -m -J "gen" -M "AndroidManifest.xml" -S "res" -I "D:/Android/sdk\platforms\android-27\android.jar" -F bin/resources.ap_ --extra-packages android.support.graphics.drawable.animated:android.support.v7.appcompat:android.support.v7.cardview:com.unity.purchasing:android.support.customtabs:com.facebook:com.facebook.android:com.android.vending.billing:com.unity.purchasing.googleplay:com.google.example.games.mainlibproj:com.google.games.bridge:com.google.android.gms.ads.impl:com.google.android.gms.ads:com.google.android.gms.auth.api:com.google.android.gms.auth:com.google.android.gms.base:com.google.android.gms.base:com.google.android.gms:com.google.android.gms:com.google.android.gms.drive:com.google.android.gms.games:com.google.android.gms.nearby:com.google.android.gms.safetynet:com.google.android.gms.tasks:android.support.compat:android.support.coreui:android.support.coreutils:android.support.fragment:android.support.mediacompat:android.support.v4:android.support.graphics.drawable:com.google.ads.mediation.unity:com.unity3d.ads -S "MY_PROJECT\Temp\StagingArea\android-libraries\animated-vector-drawable-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\cardview-v7-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\common\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\customtabs-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-wrapper-7.10.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\GoogleAIDL\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\GooglePlay\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\gpgs-plugin-support-0.9.42\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-ads-11.0.2\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-ads-lite-11.0.2\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-auth-10.2.6\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-auth-base-10.2.6\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-base-10.2.6\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-base-11.0.2\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-basement-10.2.6\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-basement-11.0.2\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-drive-10.2.6\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-games-10.2.6\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-nearby-10.2.6\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-safetynet-11.0.2\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\play-services-tasks-10.2.6\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\support-compat-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\support-core-ui-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\support-core-utils-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\support-fragment-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\support-media-compat-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\support-v4-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\support-vector-drawable-25.3.1\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\unity-adapter-2.1.0.0\res" -S "MY_PROJECT\Temp\StagingArea\android-libraries\unity-ads-sdk-2.1\res"

stderr[
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\layout\abc_alert_dialog_button_bar_material.xml:18: note: removing attribute http://schemas.android.com/apk/res/android:scrollIndicators from <ScrollView>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\layout\abc_alert_dialog_button_bar_material.xml: note: using v22 attributes; synthesizing resource com.puppeteergames.breakit:layout/abc_alert_dialog_button_bar_material for configuration v22.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\layout\abc_screen_toolbar.xml:27: note: removing attribute http://schemas.android.com/apk/res/android:touchscreenBlocksFocus from <android.support.v7.widget.ActionBarContainer>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\layout\abc_screen_toolbar.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:layout/abc_screen_toolbar for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_ab_back_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_ab_back_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_ab_back_material.xml:24: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_ab_back_material.xml:24: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_ab_back_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ic_ab_back_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_arrow_drop_right_black_24dp.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_arrow_drop_right_black_24dp.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_arrow_drop_right_black_24dp.xml:31: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_arrow_drop_right_black_24dp.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_arrow_drop_right_black_24dp.xml:30: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_arrow_drop_right_black_24dp.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ic_arrow_drop_right_black_24dp for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_clear_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_clear_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_clear_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_clear_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_clear_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ic_clear_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_go_search_api_material.xml:16: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_go_search_api_material.xml:16: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_go_search_api_material.xml:22: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_go_search_api_material.xml:22: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_go_search_api_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ic_go_search_api_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_menu_overflow_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_menu_overflow_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_menu_overflow_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_menu_overflow_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_menu_overflow_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ic_menu_overflow_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_search_api_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_search_api_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_search_api_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_search_api_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_search_api_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ic_search_api_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_voice_search_api_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_voice_search_api_material.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_voice_search_api_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_voice_search_api_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ic_voice_search_api_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ic_voice_search_api_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ratingbar_indicator_material.xml:25: note: removing attribute http://schemas.android.com/apk/res/android:tileModeX from <bitmap>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ratingbar_indicator_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ratingbar_indicator_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ratingbar_material.xml:25: note: removing attribute http://schemas.android.com/apk/res/android:tileModeX from <bitmap>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ratingbar_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ratingbar_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ratingbar_small_material.xml:23: note: removing attribute http://schemas.android.com/apk/res/android:tileModeX from <bitmap>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_ratingbar_small_material.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_ratingbar_small_material for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_vector_test.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_vector_test.xml:17: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_vector_test.xml:22: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_vector_test.xml:22: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\appcompat-v7-25.3.1\res\drawable\abc_vector_test.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/abc_vector_test for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_button_login_logo.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_button_login_logo.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_button_login_logo.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_button_login_logo.xml:28: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_button_login_logo.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/com_facebook_button_login_logo for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_favicon_blue.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:viewportHeight from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_favicon_blue.xml:21: note: removing attribute http://schemas.android.com/apk/res/android:viewportWidth from <vector>
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_favicon_blue.xml:26: note: removing attribute http://schemas.android.com/apk/res/android:fillColor from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_favicon_blue.xml:26: note: removing attribute http://schemas.android.com/apk/res/android:pathData from <path>
MY_PROJECT\Temp\StagingArea\android-libraries\facebook-android-sdk-4.23.0\res\drawable\com_facebook_favicon_blue.xml: note: using v21 attributes; synthesizing resource com.puppeteergames.breakit:drawable/com_facebook_favicon_blue for configuration v21.
MY_PROJECT\Temp\StagingArea\android-libraries\play-services-base-10.2.6\res\values\values.xml:33: error: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
MY_PROJECT\Temp\StagingArea\android-libraries\play-services-base-11.0.2\res\values\values.xml:34: Original attribute defined here.
MY_PROJECT\Temp\StagingArea\android-libraries\play-services-base-10.2.6\res\values\values.xml:46: error: Attribute "buttonSize" already defined with incompatible format.
MY_PROJECT\Temp\StagingArea\android-libraries\play-services-base-11.0.2\res\values\values.xml:47: Original attribute defined here.
MY_PROJECT\Temp\StagingArea\android-libraries\play-services-base-10.2.6\res\values\values.xml:54: error: Attribute "colorScheme" already defined with incompatible format.
MY_PROJECT\Temp\StagingArea\android-libraries\play-services-base-11.0.2\res\values\values.xml:55: Original attribute defined here.
]

**Comment by UncleBeng** [comment]
1. For  first look this four .arr files making the problem(Assets/Plugins/Android):
play-services-base-10.2.6 -> remove 
play-services-base-11.0.2
play-services-basement-10.2.6 -> remove
play-services-basement-11.0.2
You can try building the project after removing this two files, but it probably still would't work.
2. Next step is to replace all play-services-xxxx-10.2.6.arr files by play-services-xxxx-11.0.2.arr(you can find it in your Android sdk, path: sdk\extras\google\m2repository\com\google\android\gms)

**Comment by shohagmist** [comment]
@UncleBeng Thanks a ton...Thank you so much...I didn't replace all 10.2.6 with 11.0.2 but I replaced all 11.0.2 with 10.2.6 because the GPG plug-in was not able to match for 11.0.2 version.
Thanks a lot again

**Comment by shohagmist** [comment]
@UncleBeng Thanks a ton...Thank you so much...I didn't replace all 10.2.6 with 11.0.2 but I replaced all 11.0.2 with 10.2.6 because the GPG plug-in was not able to match for 11.0.2 version.
Thanks a lot again
