### ISSUE TITLE
[Exception] Build fail with AdMob and Unity IAP for Android

### ISSUE THREAD

**Issue by Roixo** [unity-plugins/Unity-Admob#84]
Hi,
I try to build my project for Android and i get this error. I have read that it is because I use Unity IAP as well. Any tip how to fix it? I just updated my jdk to the latest version. Where is the com/unity3d/ads/BuildConfig folder?

CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_172\bin\java.exe -classpath "C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.0.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: **Multiple dex files define Lcom/unity3d/ads/BuildConfig**;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 34s
]
stdout[
Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Android\Sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:prepareAdmoblibReleaseLibrary
:prepareAppcompatV72610Library
:prepareCommonLibrary
:prepareGoogleAIDLLibrary
:prepareGooglePlayLibrary
:preparePlayServicesAds1180Library
:preparePlayServicesAdsLite1180Library
:preparePlayServicesBasement1180Library
:preparePlayServicesGass1180Library
:prepareSupportCompat2610Library
:prepareSupportV42610Library
:prepareUnityAdapter2100Library
:prepareUnityAdsLibrary
:prepareUnityAdsSdk21Library
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard
:javaPreCompileRelease
:compileReleaseJavaWithJavac
:compileReleaseNdk NO-SOURCE
:compileReleaseSources
:lintVitalRelease
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:transformClassesWithDexForRelease FAILED
31 actionable tasks: 26 executed, 5 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1 progress, System.String error)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by Roixo** [comment]
Finally i used this plugin and works fine:

https://github.com/googleads/googleads-mobile-unity

**Comment by unity-plugins** [comment]
Fixed and updated ,enjoy it now.

**Comment by z5084633** [comment]
Hi, i am getting this exact error message after installing the AdMod plugin and trying to build my project. any ideas on how to fix this issue?

**Comment by unity-plugins** [comment]
com.android.dex.DexException: Multiple dex files define Lcom/unity3d/ads/BuildConfig     ？
remove unityads.aar

ndk error?
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory. It is currently set to C:\Android\Sdk\ndk-bundle.

set ndk path

**Comment by z5084633** [comment]
Thanks for helping. Had both of those errors, I managed to fix the NDK error by setting the correct directory but not the Multiple dex file error. cant seem to find this unityads.aar file. Did a search on my whole computer.

**Comment by z5084633** [comment]
Deleting unity-ads-sdk-2.1.aar seemed to do the trick.

**Comment by DrPro6757** [comment]
Having this error in unity after integrating google mobile ads and google services
Plz need help to resolve this
CommandInvokationFailure: Gradle build failed. 
C:/Program Files/Java/jdk1.8.0_31\bin\java.exe -classpath "C:\Program Files\Unity 2017.4.8.f1\Unity\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\gradle\lib\gradle-launcher-4.0.1.jar" org.gradle.launcher.GradleMain "-Dorg.gradle.jvmargs=-Xmx2048m" "assembleRelease"

stderr[

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 21s
]
stdout[
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to E:\Setups\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to E:\Setups\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

The setTestClassesDir(File) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the setTestClassesDirs(FileCollection) method instead.
The getTestClassesDir() method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the getTestClassesDirs() method instead.
The ConfigurableReport.setDestination(Object) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use the method ConfigurableReport.setDestination(File) instead.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to E:\Setups\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:preDebugBuild UP-TO-DATE
:prepareAppcompatV72340Library
:prepareComAndroidSupportSupportCompat2520Library
:prepareComAndroidSupportSupportCoreUi2520Library
:prepareComAndroidSupportSupportCoreUtils2520Library
:prepareComAndroidSupportSupportFragment2520Library
:prepareComAndroidSupportSupportMediaCompat2520Library
:prepareComAndroidSupportSupportV42520Library
:prepareComGoogleAndroidGmsPlayServicesAuth1162Library
:prepareComGoogleAndroidGmsPlayServicesAuthApiPhone1162Library
:prepareComGoogleAndroidGmsPlayServicesAuthApiPhoneLicense1162Library
:prepareComGoogleAndroidGmsPlayServicesAuthBase1162Library
:prepareComGoogleAndroidGmsPlayServicesAuthBaseLicense1162Library
:prepareComGoogleAndroidGmsPlayServicesBase1162Library
:prepareComGoogleAndroidGmsPlayServicesBaseLicense1162Library
:prepareComGoogleAndroidGmsPlayServicesBasement1162Library
:prepareComGoogleAndroidGmsPlayServicesBasementLicense1162Library
:prepareComGoogleAndroidGmsPlayServicesDrive1162Library
:prepareComGoogleAndroidGmsPlayServicesDriveLicense1162Library
:prepareComGoogleAndroidGmsPlayServicesGames1162Library
:prepareComGoogleAndroidGmsPlayServicesGamesLicense1162Library
:prepareComGoogleAndroidGmsPlayServicesNearby1162Library
:prepareComGoogleAndroidGmsPlayServicesNearbyLicense1162Library
:prepareComGoogleAndroidGmsPlayServicesTasks1162Library
:prepareComGoogleAndroidGmsPlayServicesTasksLicense1162Library
:prepareComGoogleGamesGpgsPluginSupport0950Library
:preparePlayServicesAds1001Library
:preparePlayServicesAdsLite1001Library
:preparePlayServicesBase1001Library
:preparePlayServicesBasement1001Library
:prepareSupportV42400Library
:prepareUnityAdsLibrary
:GooglePlayGamesManifest.plugin:preBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:preReleaseBuild UP-TO-DATE
:GooglePlayGamesManifest.plugin:checkReleaseManifest
:GooglePlayGamesManifest.plugin:prepareReleaseDependencies
:GooglePlayGamesManifest.plugin:compileReleaseAidl
:GooglePlayGamesManifest.plugin:compileReleaseNdk NO-SOURCE
:GooglePlayGamesManifest.plugin:compileLint
:GooglePlayGamesManifest.plugin:copyReleaseLint NO-SOURCE
:GooglePlayGamesManifest.plugin:mergeReleaseShaders
:GooglePlayGamesManifest.plugin:compileReleaseShaders
:GooglePlayGamesManifest.plugin:generateReleaseAssets
:GooglePlayGamesManifest.plugin:mergeReleaseAssets
:GooglePlayGamesManifest.plugin:mergeReleaseProguardFiles UP-TO-DATE
:GooglePlayGamesManifest.plugin:packageReleaseRenderscript NO-SOURCE
:GooglePlayGamesManifest.plugin:compileReleaseRenderscript
:GooglePlayGamesManifest.plugin:generateReleaseResValues
:GooglePlayGamesManifest.plugin:generateReleaseResources
:GooglePlayGamesManifest.plugin:packageReleaseResources
:GooglePlayGamesManifest.plugin:processReleaseManifest
:GooglePlayGamesManifest.plugin:generateReleaseBuildConfig
:GooglePlayGamesManifest.plugin:processReleaseResources
:GooglePlayGamesManifest.plugin:generateReleaseSources
:GooglePlayGamesManifest.plugin:incrementalReleaseJavaCompilationSafeguard
:GooglePlayGamesManifest.plugin:javaPreCompileRelease
:GooglePlayGamesManifest.plugin:compileReleaseJavaWithJavac
:GooglePlayGamesManifest.plugin:processReleaseJavaRes NO-SOURCE
:GooglePlayGamesManifest.plugin:transformResourcesWithMergeJavaResForRelease
:GooglePlayGamesManifest.plugin:transformClassesAndResourcesWithSyncLibJarsForRelease
:GooglePlayGamesManifest.plugin:mergeReleaseJniLibFolders
:GooglePlayGamesManifest.plugin:transformNativeLibsWithMergeJniLibsForRelease
:GooglePlayGamesManifest.plugin:transformNativeLibsWithSyncJniLibsForRelease
:GooglePlayGamesManifest.plugin:bundleRelease
:Heyzap:preBuild UP-TO-DATE
:Heyzap:preReleaseBuild UP-TO-DATE
:Heyzap:checkReleaseManifest
:Heyzap:prepareReleaseDependencies
:Heyzap:compileReleaseAidl
:Heyzap:compileReleaseNdk NO-SOURCE
:Heyzap:compileLint
:Heyzap:copyReleaseLint NO-SOURCE
:Heyzap:mergeReleaseShaders
:Heyzap:compileReleaseShaders
:Heyzap:generateReleaseAssets
:Heyzap:mergeReleaseAssets
:Heyzap:mergeReleaseProguardFiles UP-TO-DATE
:Heyzap:packageReleaseRenderscript NO-SOURCE
:Heyzap:compileReleaseRenderscript
:Heyzap:generateReleaseResValues
:Heyzap:generateReleaseResources
:Heyzap:packageReleaseResources
:Heyzap:processReleaseManifest
:Heyzap:generateReleaseBuildConfig
:Heyzap:processReleaseResources
:Heyzap:generateReleaseSources
:Heyzap:incrementalReleaseJavaCompilationSafeguard
:Heyzap:javaPreCompileRelease
:Heyzap:compileReleaseJavaWithJavac
:Heyzap:processReleaseJavaRes NO-SOURCE
:Heyzap:transformResourcesWithMergeJavaResForRelease
:Heyzap:transformClassesAndResourcesWithSyncLibJarsForRelease
:Heyzap:mergeReleaseJniLibFolders
:Heyzap:transformNativeLibsWithMergeJniLibsForRelease
:Heyzap:transformNativeLibsWithSyncJniLibsForRelease
:Heyzap:bundleRelease
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript UP-TO-DATE
:generateReleaseBuildConfig UP-TO-DATE
:generateReleaseResValues UP-TO-DATE
:generateReleaseResources UP-TO-DATE
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:javaPreCompileRelease
:compileReleaseJavaWithJavac UP-TO-DATE
:compileReleaseNdk NO-SOURCE
:compileReleaseSources UP-TO-DATE
:lintVitalRelease
:mergeReleaseShaders UP-TO-DATE
:compileReleaseShaders UP-TO-DATE
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:transformClassesWithDexForRelease FAILED
94 actionable tasks: 85 executed, 9 up-to-date
]
exit code: 1
UnityEditor.Android.Command.WaitForProgramToRun (UnityEditor.Utils.Program p, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.Command.Run (System.Diagnostics.ProcessStartInfo psi, UnityEditor.Android.WaitingForProcessToExit waitingForProcessToExit, System.String errorMsg)
UnityEditor.Android.AndroidJavaTools.RunJava (System.String args, System.String workingdir, System.Action`1 progress, System.String error)
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
Rethrow as GradleInvokationException: Gradle build failed
UnityEditor.Android.GradleWrapper.Run (System.String workingdir, System.String task, System.Action`1 progress)
UnityEditor.Android.PostProcessor.Tasks.BuildGradleProject.Execute (UnityEditor.Android.PostProcessor.PostProcessorContext context)
UnityEditor.Android.PostProcessor.PostProcessRunner.RunAllTasks (UnityEditor.Android.PostProcessor.PostProcessorContext context)

**Comment by unity-plugins** [comment]
https://github.com/unity-plugins/google-play-game-service-for-unity3d

Have a try. this have integate admob and google play service
