### ISSUE TITLE
Exception: JNI: Init'd AndroidJavaClass with null ptr!

### ISSUE THREAD

**Issue by frankiefanstar** [unity-plugins/Unity-Admob#9]
When I want to Play the demo in Editor Mode, this error will come out.

Exception: JNI: Init'd AndroidJavaClass with null ptr!
UnityEngine.AndroidJavaClass..ctor (IntPtr jclass)
UnityEngine.AndroidJavaObject.get_JavaLangClass ()
UnityEngine.AndroidJavaObject.FindClass (System.String name)
UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className)
UnityEngine.AndroidJavaClass..ctor (System.String className)
admob.Admob.preInitAdmob () (at Assets/Plugins/AdmobAPI/Admob.cs:139)
admob.Admob.Instance () (at Assets/Plugins/AdmobAPI/Admob.cs:20)

**Comment by ForwardForward** [comment]
The same problem in Unity 5.3.5

**Comment by unity-plugins** [comment]
it a bug of unity editor,if you never published android platform ,it will work well
