### ISSUE TITLE
Video Ads Not Showing

### ISSUE THREAD

**Issue by richnaisanze** [unity-plugins/Unity-Admob#94]
I have set up my Admob Plugin with Unity in a test/empty project, in case to reproduce and test this feature.

I'm having troubles showing the video ads. I'm using the same script that I've used in my project before (it worked fine) and the newest plugin.

The trouble is video ads keep showing "isLoaded : false" and error "No Fill", while the banner and interstitial ads work fine. I don't know what is affecting this???

I've tried using the "google id tests" and it worked fine, after I changed into my app and ad unit ID, it's not showing anymore.

Please anyone who having the same troubles, can share how to fix this issue. Thanks before.

**Comment by RupeshPamaihgari** [comment]
I m facing the same problem. Do we have any fix for it ?

**Comment by unity-plugins** [comment]
showing "isLoaded : false" and error "No Fill"
mean ,no ads found in admob server,not your code error.

**Comment by richnaisanze** [comment]
I work this project with my friends, and in his previous project (already published) the video loaded successfully after a single try. 

While in our project now (not published yet), the video loads keep showing "no fill" after trying to load the video ten times and more.

So, is there any difference between published or non-published app for the "available" video ads in admob server?

Anyway, thanks for your reply. I just curious about this 😆

**Comment by unity-plugins** [comment]
Updated ,have a try again

**Comment by richnaisanze** [comment]
That was quick. I'll try it and will give the feedback ASAP. Thank you !
